using System;
using System.Buffers.Binary;
using System.IO;
using System.IO.Pipelines;
using System.Threading.Tasks;
using CosmoImage.Core;
using CosmoImage.Loaders;
using Xunit;

namespace CosmoImage.Tests;

/// <summary>
/// Round 148 — multi-part EXR (first part only). Multi-part files
/// have version bit 12 set, multiple null-terminated headers
/// followed by an extra null, per-part offset tables, and a 4-byte
/// part-number prefix on every chunk. We expose part 0 only;
/// non-image part 0 (deeps) returns null so the caller can fall back.
/// </summary>
public class Round148Tests
{
    [Fact]
    public void Pure_MultiPartScanlineExr_FirstPartDecodes()
    {
        // 4×2 RGB HALF, single-part-format-as-multi-part (one image part).
        int w = 4, h = 2;
        var rgb = new ushort[w * h * 3];
        for (int i = 0; i < rgb.Length; i++) rgb[i] = (ushort)((0x3C00 + i) & 0xFFFF);

        var exr = BuildMultiPartScanlineExr(rgb, w, h, partType: "scanlineimage");
        var img = PureExrDecoder.TryDecode(exr);
        Assert.NotNull(img);
        Assert.Equal(w, img!.Width);
        Assert.Equal(h, img.Height);
        Assert.Equal(3, img.Bands);

        var got = ReadFloats(img.PixelsLazy!.Value);
        for (int i = 0; i < rgb.Length; i++)
        {
            float expected = (float)BitConverter.UInt16BitsToHalf(rgb[i]);
            Assert.Equal(expected, got[i]);
        }
    }

    /// <summary>
    /// Two-part EXR generated by Python's OpenEXR module (libOpenEXR
    /// 3.4): part 0 = scanlineimage RGB-HALF, part 1 = scanlineimage
    /// Z-depth FLOAT. Validates against the canonical reference.
    /// </summary>
    private const string LibimfTwoPartExrBase64 =
        "di8xAQIQAABjaGFubmVscwBjaGxpc3QANwAAAEIAAQAAAAAAAAABAAAAAQAAAEcAAQAAAAAAAAABAAAAAQAAAFIAAQAAAAAAAAABAAAAAQAAAABjaHVua0NvdW50AGludAAEAAAAAgAAAGNvbXByZXNzaW9uAGNvbXByZXNzaW9uAAEAAAAAZGF0YVdpbmRvdwBib3gyaQAQAAAAAAAAAAAAAAADAAAAAQAAAGRpc3BsYXlXaW5kb3cAYm94MmkAEAAAAAAAAAAAAAAAAwAAAAEAAABsaW5lT3JkZXIAbGluZU9yZGVyAAEAAAAAbmFtZQBzdHJpbmcABwAAAHByaW1hcnlwaXhlbEFzcGVjdFJhdGlvAGZsb2F0AAQAAAAAAIA/c2NyZWVuV2luZG93Q2VudGVyAHYyZgAIAAAAAAAAAAAAAABzY3JlZW5XaW5kb3dXaWR0aABmbG9hdAAEAAAAAACAP3R5cGUAc3RyaW5nAA0AAABzY2FubGluZWltYWdlAGNoYW5uZWxzAGNobGlzdAATAAAAWgACAAAAAAAAAAEAAAABAAAAAGNodW5rQ291bnQAaW50AAQAAAACAAAAY29tcHJlc3Npb24AY29tcHJlc3Npb24AAQAAAABkYXRhV2luZG93AGJveDJpABAAAAAAAAAAAAAAAAMAAAABAAAAZGlzcGxheVdpbmRvdwBib3gyaQAQAAAAAAAAAAAAAAADAAAAAQAAAGxpbmVPcmRlcgBsaW5lT3JkZXIAAQAAAABuYW1lAHN0cmluZwAFAAAAZGVwdGhwaXhlbEFzcGVjdFJhdGlvAGZsb2F0AAQAAAAAAIA/c2NyZWVuV2luZG93Q2VudGVyAHYyZgAIAAAAAAAAAAAAAABzY3JlZW5XaW5kb3dXaWR0aABmbG9hdAAEAAAAAACAP3R5cGUAc3RyaW5nAA0AAABzY2FubGluZWltYWdlAAD7AgAAAAAAAB8DAAAAAAAAQwMAAAAAAABfAwAAAAAAAAAAAAAAAAAAGAAAAAAAACQAKAAqAAAALwAzQDUAAAAtADGAMwAAAAABAAAAGAAAAAAkAAAAKgAogDGANEA2ADgAKgAwgDKANAEAAAAAAAAAEAAAAAAAAD8AAAA/AAAAPwAAAD8BAAAAAQAAABAAAAAAAAA/AAAAPwAAAD8AAAA/";

    [Fact]
    public void Pure_LibimfTwoPartExr_DecodesPart0Exactly()
    {
        // Two-part libimf EXR: part 0 = RGB-HALF, part 1 = depth-FLOAT.
        // Our decoder returns part 0 only. Tests we read past part 1's
        // metadata correctly (chunkCount, names, etc.) and decode the
        // first part's pixels bit-exactly.
        var bytes = Convert.FromBase64String(LibimfTwoPartExrBase64);
        var img = PureExrDecoder.TryDecode(bytes);
        Assert.NotNull(img);
        Assert.Equal(4, img!.Width);
        Assert.Equal(2, img.Height);
        Assert.Equal(3, img.Bands);

        var got = ReadFloats(img.PixelsLazy!.Value);
        for (int y = 0; y < 2; y++)
        {
            for (int x = 0; x < 4; x++)
            {
                float expR = (float)(Half)(((x * 5 + y * 3) % 64) / 64.0);
                float expG = (float)(Half)(((x * 7 + y * 11) % 64) / 64.0);
                float expB = (float)(Half)((x ^ y) / 64.0);
                int o = (y * 4 + x) * 3;
                Assert.Equal(expR, got[o]);
                Assert.Equal(expG, got[o + 1]);
                Assert.Equal(expB, got[o + 2]);
            }
        }
    }

    [Fact]
    public void Pure_MultiPartDeepFirst_RejectsPart0()
    {
        // Multi-part with part 0 = deepscanline (we don't support deeps).
        // The decoder should return null so the caller falls back.
        var exr = BuildMultiPartScanlineExr(new ushort[6], 2, 1, partType: "deepscanline");
        var img = PureExrDecoder.TryDecode(exr);
        Assert.Null(img);
    }

    /// <summary>
    /// Hand-build a one-part multi-part scanline EXR. Layout: magic +
    /// version-with-bit-12 + header + null + extra null + offset table +
    /// per-chunk(4-byte part number + yCoord + dataSize + pixel data).
    /// </summary>
    private static byte[] BuildMultiPartScanlineExr(ushort[] rgb, int w, int h, string partType)
    {
        using var ms = new MemoryStream();
        WriteI32(ms, 0x01312F76);
        WriteI32(ms, 2 | 0x1000);  // version 2 + multiPart bit

        // Header — channels alphabetical (B, G, R), no compression,
        // 1 scanline per chunk, plus the multi-part-required type / name /
        // chunkCount attributes.
        WriteAttribute(ms, "channels", "chlist", buf =>
        {
            WriteChannel(buf, "B");
            WriteChannel(buf, "G");
            WriteChannel(buf, "R");
            buf.WriteByte(0);
        });
        WriteAttribute(ms, "compression", "compression", buf => buf.WriteByte(0));
        WriteAttribute(ms, "dataWindow", "box2i", buf =>
        { WriteI32(buf, 0); WriteI32(buf, 0); WriteI32(buf, w - 1); WriteI32(buf, h - 1); });
        WriteAttribute(ms, "displayWindow", "box2i", buf =>
        { WriteI32(buf, 0); WriteI32(buf, 0); WriteI32(buf, w - 1); WriteI32(buf, h - 1); });
        WriteAttribute(ms, "lineOrder", "lineOrder", buf => buf.WriteByte(0));
        WriteAttribute(ms, "pixelAspectRatio", "float", buf => WriteF32(buf, 1.0f));
        WriteAttribute(ms, "screenWindowCenter", "v2f", buf => { WriteF32(buf, 0); WriteF32(buf, 0); });
        WriteAttribute(ms, "screenWindowWidth", "float", buf => WriteF32(buf, 1.0f));
        WriteAttribute(ms, "type", "string", buf => buf.Write(System.Text.Encoding.ASCII.GetBytes(partType)));
        WriteAttribute(ms, "name", "string", buf => buf.Write(System.Text.Encoding.ASCII.GetBytes("main")));
        // chunkCount = h (one scanline per chunk for NO_COMPRESSION).
        WriteAttribute(ms, "chunkCount", "int", buf => WriteI32(buf, h));
        ms.WriteByte(0);    // header terminator

        // Multi-part end-of-headers marker.
        ms.WriteByte(0);

        // Offset table for part 0 — patched after we know each chunk's start.
        long offsetTablePos = ms.Position;
        for (int y = 0; y < h; y++) WriteI64(ms, 0);

        for (int y = 0; y < h; y++)
        {
            long blockStart = ms.Position;
            long savedPos = ms.Position;
            ms.Position = offsetTablePos + y * 8;
            WriteI64(ms, blockStart);
            ms.Position = savedPos;

            WriteI32(ms, 0);    // multi-part chunk prefix: part number = 0
            WriteI32(ms, y);    // yCoord
            int dataSize = 3 * w * 2;
            WriteI32(ms, dataSize);

            // Channel-major pixel data (B then G then R per row).
            for (int x = 0; x < w; x++) WriteHalfBytes(ms, rgb[(y * w + x) * 3 + 2]);  // B
            for (int x = 0; x < w; x++) WriteHalfBytes(ms, rgb[(y * w + x) * 3 + 1]);  // G
            for (int x = 0; x < w; x++) WriteHalfBytes(ms, rgb[(y * w + x) * 3 + 0]);  // R
        }

        return ms.ToArray();
    }

    private static void WriteChannel(Stream s, string name)
    {
        foreach (char c in name) s.WriteByte((byte)c);
        s.WriteByte(0);
        WriteI32(s, 1);  // pixelType = HALF
        s.WriteByte(0);
        s.WriteByte(0); s.WriteByte(0); s.WriteByte(0);
        WriteI32(s, 1); WriteI32(s, 1);
    }

    private static void WriteAttribute(Stream s, string name, string type, Action<MemoryStream> writeValue)
    {
        foreach (char c in name) s.WriteByte((byte)c);
        s.WriteByte(0);
        foreach (char c in type) s.WriteByte((byte)c);
        s.WriteByte(0);
        using var ms = new MemoryStream();
        writeValue(ms);
        var data = ms.ToArray();
        WriteI32(s, data.Length);
        s.Write(data, 0, data.Length);
    }

    private static void WriteI32(Stream s, int v) { Span<byte> b = stackalloc byte[4]; BinaryPrimitives.WriteInt32LittleEndian(b, v); s.Write(b); }
    private static void WriteI64(Stream s, long v) { Span<byte> b = stackalloc byte[8]; BinaryPrimitives.WriteInt64LittleEndian(b, v); s.Write(b); }
    private static void WriteF32(Stream s, float v) => WriteI32(s, BitConverter.SingleToInt32Bits(v));
    private static void WriteHalfBytes(Stream s, ushort h)
    {
        Span<byte> b = stackalloc byte[2];
        BinaryPrimitives.WriteUInt16LittleEndian(b, h);
        s.Write(b);
    }

    private static float[] ReadFloats(byte[] raw)
    {
        var f = new float[raw.Length / 4];
        Buffer.BlockCopy(raw, 0, f, 0, raw.Length);
        return f;
    }
}
